# Configuração do pytest
# Define como e onde executar os testes

[pytest]
pythonpath = .      # Adiciona raiz do projeto ao PYTHONPATH
testpaths = tests   # Define pasta onde os testes estão localizados
