name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-livros-docker-demo

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt

      - run: pylint *.py --fail-under=7.0

      - run: pytest --cov=. --cov-fail-under=70 --cov-config=.coveragerc

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: docker build -t catalogo-livros ./api-livros-docker-demo
